### ISSUE TITLE
Blocks: Block Drop

### ISSUE THREAD

**Issue by AVATAR-Phoenix** [chraft/c-raft#100]
When a block is surrounded by leaves and it is destroyed it doesn't drop correctly .

**Comment by ementalo** [comment]
Applies to other things not just leaves

**Comment by taugit** [comment]
It's not a block bug. Spawned items aren't affected by a gravity while client expects them to fall on the ground. If the player is out of the pickup range, the item will stay at the location where it was spawned. Client will show falling animation and flip item back upon the next entity update packet that it receive from the server.
Proper item behavior requires implemented BoundingBoxes (for collission detection) and item physics (which is not even planned for now).
Since it's just a feature that isn't implemented yet I'm closing the ticket.

P.S: You can move to the _real_ location and the item will be immediately picked up. After that flipping animation will be removed.
