### ISSUE TITLE
Newly created entities (both items and livings) aren't displayed in a client

### ISSUE THREAD

**Issue by taugit** [chraft/c-raft#129]
Created entities - items, mobs - are not displayed in the client. They definetely being created server-side (you can pick up a destroyed block even if you don't see it), but aren't send to the client.
I've noticed it few days ago, but haven't paid attention. I hope this bug wasn't introduced by me as a couple of previously fixed.
How to reproduce:
Destroy any block or use the /spawnmob command.

**Comment by Smjert** [comment]
That's because you need to call UpdateEntities on the player and use SendEntityToNearbyClients. You also make me think about a "little" fix: the last function doesn't add the entity to the loadedentity list of the client, so the packet will be sent twice.

**Comment by justinstenning** [comment]
Do we need to explicitly call UpdateEntities?

E.g. the Mob spawner could add quite a few new entities during it's spawn loop across the chunks, do I need to call update entity each time?

**Comment by Smjert** [comment]
No, UpdateEntities is owned by the player, so if there's something that the player did to add an entity, then run its UpdateEntities and SendEntityToNearbyPlayers, otherwise only the second should be called.
If you're concerned about the multiple loop over all the clients in the server.. well we can implement sectors, each of them has a list of clients/entities in it, this way found the sectors involved you can loop through few entities.

Edit: i think about sectors as a group of chunks, something like 4x4 chunks.

**Comment by taugit** [comment]
Fixed by spazzarama in [this commit](https://github.com/chraft/c-raft/commit/2fe26c33c903b62f7c8ea4a7c1024d1b3eff37bc)
